<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFxwDBdD\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFxwDBdD/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerFxwDBdD.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerFxwDBdD\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerFxwDBdD\App_KernelProdContainer([
    'container.build_hash' => 'FxwDBdD',
    'container.build_id' => '23c73bbf',
    'container.build_time' => 1677152693,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFxwDBdD');
