<?php

namespace Container066L4bq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RKPXoYBService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.RKPXoYB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.RKPXoYB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'cache' => ['services', 'cache.app', 'getCache_AppService', true],
            'httpClient' => ['privates', 'http_client', 'getHttpClientService', true],
        ], [
            'cache' => '?',
            'httpClient' => '?',
        ]);
    }
}
