<?php

namespace ContainerX5SPxg7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RY6YCt1Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rY6YCt1' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.rY6YCt1'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'cache' => ['services', 'cache.app', 'getCache_AppService', false],
            'httpClient' => ['privates', '.debug.http_client', 'get_Debug_HttpClientService', false],
            'mixRepository' => ['privates', 'App\\Service\\MixRepository', 'getMixRepositoryService', true],
        ], [
            'cache' => '?',
            'httpClient' => '?',
            'mixRepository' => 'App\\Service\\MixRepository',
        ]);
    }
}
