<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerA2tGPOO\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerA2tGPOO/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerA2tGPOO.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerA2tGPOO\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerA2tGPOO\App_KernelDevDebugContainer([
    'container.build_hash' => 'A2tGPOO',
    'container.build_id' => '7e407ac3',
    'container.build_time' => 1677499566,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerA2tGPOO');
