<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX5SPxg7\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX5SPxg7/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerX5SPxg7.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerX5SPxg7\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerX5SPxg7\App_KernelDevDebugContainer([
    'container.build_hash' => 'X5SPxg7',
    'container.build_id' => 'bcb46a2e',
    'container.build_time' => 1677576675,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX5SPxg7');
